### ISSUE TITLE
Issue with the create phar/zip button

### ISSUE THREAD

**Issue by MalakasPlayzMC** [pmt-mcpe-fun/web.app#14]
I have to edit the website every time to use the create phar/zip button to work. I cannot press it

**Comment by Ad5001** [comment]
Ok. Browser ? OS?

**Comment by MalakasPlayzMC** [comment]
Mozilla 48.0b6 - Windows 7

**Comment by MalakasPlayzMC** [comment]
Mozilla 48.0b6 - Windows 7

**Comment by Ad5001** [comment]
Works complitly fine for me with Mozilla 54. Try updating your browser?

**Comment by NFGamerMC** [comment]
You need to click exactly on the text, we officially support Chrome though. Try that and respond if further issues are discovered.

**Comment by MalakasPlayzMC** [comment]
Ok, just updated to Mozilla 54, issue fixed, please lock
