### ISSUE TITLE
API Changes, Will not convert to 3.0.0-ALPHA7: Issue 1

### ISSUE THREAD

**Issue by BlawoHD** [pmt-mcpe-fun/web.app#15]
Can you possibly do the changed things from the api 3.0.0-ALPHA6 to the 3.0.0-ALPHA7?

**Comment by Ad5001** [comment]
Yes. I'll be working on that soon. Just need to finish PSM.

**Comment by NFGamerMC** [comment]
That is something needed as ALPHA7 did have some breaking changes as every ALPHA build does. Standby and when PSM is complete we will work on this.

**Comment by NFGamerMC** [comment]
This issue will be closed for spam sake, this does not mean we cannot help but this is a WIP. Reply to this if you require any more information on this topic.
