### ISSUE TITLE
API Changes, Will not convert to 3.0.0-ALPHA7: Issue 2

### ISSUE THREAD

**Issue by smakosav** [pmt-mcpe-fun/web.app#16]
The plugin in question is called Iprotector I try to update the bees, but from this error:

[19:38:16]  [Server thread/INFO]: Loading iProtector

`Fatal error: Declaration of LDX\iProtector\Main::onCommand(pocketmine\command\CommandSender $p, pocketmine\command\Command $cmd, $label, array $args) must be compatible with pocketmine\command\CommandExecutor::onCommand(pocketmine\command\CommandSender $sender, pocketmine\command\Command $command, string $label, array $args): bool in phar:///Users/gabriele/Desktop/pocketmine/pocketmine-mp.git/plugins/iProtector.phar/src/LDX/iProtector/Main.php on line 18
[19:38:16] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[19:38:16] [Server thread/EMERGENCY]: Please upload the "/Users/gabriele/Desktop/pocketmine/pocketmine-mp.git/crashdumps/Wed_Aug_2-19.38.16-CEST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.`

The reason? 
I tried everything in both ways (API injection or replacement in plugin.yml file "unphar" from 2.0.0 to 3.0.0-ALPHA7).
Finally someone could do it in my place, saving me a little complicated for me,
Or if you can explain the procedure, I'm not entirely ignorant of the argument.

Plugin downloaded from here: https://github.com/LDX-MCPE/iProtector

**Comment by NFGamerMC** [comment]
This is an issue caused by the updating of the PocketMine API. We have currently not provided a fix just yet but if you standby when we have time we will help you. I may recommend going to [Poggit](https://poggit.pmmp.io) if you wish to find other plugins.

**Comment by NFGamerMC** [comment]
This issue will be closed for spam sake, this does not mean we cannot help but this is a WIP. Reply to this if you require any more information on this topic.

**Comment by smakosav** [comment]
Excuse for involuntary spam, updated comment.

**Comment by smakosav** [comment]
@NFGamerMC Have you already thought about how to update or correct? I hope it's a way, if not, to rewrite the plugin from scratch  :[

**Comment by Ad5001** [comment]
Pretty simple, here's what you have to replace in src:
https://github.com/pmmp/PocketMine-MP/commit/46a2e6cbf8f1fd71e632b1d3b4ccc34492683721

**Comment by smakosav** [comment]
@Ad5001 thanks!! you are saver! lol

**Comment by smakosav** [comment]
@Ad5001 hey friend,i write again, this problem only gives it with .phar v1.1.0.55, trying with version 1.1.4 (genesysPro) just change the API and the problem disappears.
Ps: This way your bee injector will return useful!
bye bye :)

**Comment by NFGamerMC** [comment]
@smakosav Use pmmp
