### ISSUE TITLE
makephar

### ISSUE THREAD

**Issue by AyyItzJ4y** [pmt-mcpe-fun/web.app#19]
hey so when ever I put a .zip file in the input it wouldn't let me create a phar!

**Comment by Ad5001** [comment]
OS? Browser?

**Comment by AyyItzJ4y** [comment]
Browser

**Comment by Ad5001** [comment]
Web browser (Chrome, firefox ...)
OS (Windows, MacOS, Linux...)

**Comment by AyyItzJ4y** [comment]
Chrome and Microsoft edge

**Comment by Ad5001** [comment]
Both?

**Comment by Ad5001** [comment]
What's your operating system (OS)?

**Comment by AyyItzJ4y** [comment]
? What Does that mean

**Comment by Ad5001** [comment]
Are you running Windows, MacOS, Linux...?

**Comment by AyyItzJ4y** [comment]
Oh Microsoft

**Comment by AyyItzJ4y** [comment]
Windows

**Comment by AyyItzJ4y** [comment]
So?

**Comment by Ad5001** [comment]
Have you got the latest chrome version?

**Comment by AyyItzJ4y** [comment]
Yes

**Comment by AyyItzJ4y** [comment]
Ok now Its working but Microsoft edge is not working for it

**Comment by Ad5001** [comment]
This bug has been fixed. Thanks for your patience.
