### ISSUE TITLE
Create phar not responding!

### ISSUE THREAD

**Issue by blueeagle2017** [pmt-mcpe-fun/web.app#21]
when i try to put a .zip file from my ios device it doesn’t respond.

**Comment by Ad5001** [comment]
What do you mean by "it doesn't respond"?

**Comment by blueeagle2017** [comment]
by that i mean it doesn’t upload the file to the website to create the phar file when i select the zip file i want to make into a .phar file

**Comment by blueeagle2017** [comment]
when i upload a .zip file it doesn’t show the file is uploaded and doesn’t allow me to tap the “create phar” bottom.

**Comment by nathfreder** [comment]
You must be on desktop.

**Comment by Ad5001** [comment]
Bug fixed.
